// File generated from our OpenAPI spec by Stainless.

package com.braintrustdata.api.models

import com.braintrustdata.api.models.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class EvalCreateParamsTest {

    @Test
    fun createEvalCreateParams() {
        EvalCreateParams.builder()
            .data(
                EvalCreateParams.Data.ofDatasetId(
                    EvalCreateParams.Data.DatasetId.builder().datasetId("dataset_id").build()
                )
            )
            .projectId("project_id")
            .scores(
                listOf(
                    EvalCreateParams.Score.ofFunctionId(
                        EvalCreateParams.Score.FunctionId.builder()
                            .functionId("function_id")
                            .version("version")
                            .build()
                    )
                )
            )
            .task(
                EvalCreateParams.Task.ofFunctionId(
                    EvalCreateParams.Task.FunctionId.builder()
                        .functionId("function_id")
                        .version("version")
                        .build()
                )
            )
            .baseExperimentId("base_experiment_id")
            .baseExperimentName("base_experiment_name")
            .experimentName("experiment_name")
            .gitMetadataSettings(
                EvalCreateParams.GitMetadataSettings.builder()
                    .collect(EvalCreateParams.GitMetadataSettings.Collect.ALL)
                    .fields(listOf(EvalCreateParams.GitMetadataSettings.Field.COMMIT))
                    .build()
            )
            .isPublic(true)
            .maxConcurrency(42.23)
            .metadata(EvalCreateParams.Metadata.builder().build())
            .repoInfo(
                RepoInfo.builder()
                    .authorEmail("author_email")
                    .authorName("author_name")
                    .branch("branch")
                    .commit("commit")
                    .commitMessage("commit_message")
                    .commitTime("commit_time")
                    .dirty(true)
                    .gitDiff("git_diff")
                    .tag("tag")
                    .build()
            )
            .stream(true)
            .timeout(42.23)
            .trialCount(42.23)
            .build()
    }

    @Test
    fun getBody() {
        val params =
            EvalCreateParams.builder()
                .data(
                    EvalCreateParams.Data.ofDatasetId(
                        EvalCreateParams.Data.DatasetId.builder().datasetId("dataset_id").build()
                    )
                )
                .projectId("project_id")
                .scores(
                    listOf(
                        EvalCreateParams.Score.ofFunctionId(
                            EvalCreateParams.Score.FunctionId.builder()
                                .functionId("function_id")
                                .version("version")
                                .build()
                        )
                    )
                )
                .task(
                    EvalCreateParams.Task.ofFunctionId(
                        EvalCreateParams.Task.FunctionId.builder()
                            .functionId("function_id")
                            .version("version")
                            .build()
                    )
                )
                .baseExperimentId("base_experiment_id")
                .baseExperimentName("base_experiment_name")
                .experimentName("experiment_name")
                .gitMetadataSettings(
                    EvalCreateParams.GitMetadataSettings.builder()
                        .collect(EvalCreateParams.GitMetadataSettings.Collect.ALL)
                        .fields(listOf(EvalCreateParams.GitMetadataSettings.Field.COMMIT))
                        .build()
                )
                .isPublic(true)
                .maxConcurrency(42.23)
                .metadata(EvalCreateParams.Metadata.builder().build())
                .repoInfo(
                    RepoInfo.builder()
                        .authorEmail("author_email")
                        .authorName("author_name")
                        .branch("branch")
                        .commit("commit")
                        .commitMessage("commit_message")
                        .commitTime("commit_time")
                        .dirty(true)
                        .gitDiff("git_diff")
                        .tag("tag")
                        .build()
                )
                .stream(true)
                .timeout(42.23)
                .trialCount(42.23)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.data())
            .isEqualTo(
                EvalCreateParams.Data.ofDatasetId(
                    EvalCreateParams.Data.DatasetId.builder().datasetId("dataset_id").build()
                )
            )
        assertThat(body.projectId()).isEqualTo("project_id")
        assertThat(body.scores())
            .isEqualTo(
                listOf(
                    EvalCreateParams.Score.ofFunctionId(
                        EvalCreateParams.Score.FunctionId.builder()
                            .functionId("function_id")
                            .version("version")
                            .build()
                    )
                )
            )
        assertThat(body.task())
            .isEqualTo(
                EvalCreateParams.Task.ofFunctionId(
                    EvalCreateParams.Task.FunctionId.builder()
                        .functionId("function_id")
                        .version("version")
                        .build()
                )
            )
        assertThat(body.baseExperimentId()).isEqualTo("base_experiment_id")
        assertThat(body.baseExperimentName()).isEqualTo("base_experiment_name")
        assertThat(body.experimentName()).isEqualTo("experiment_name")
        assertThat(body.gitMetadataSettings())
            .isEqualTo(
                EvalCreateParams.GitMetadataSettings.builder()
                    .collect(EvalCreateParams.GitMetadataSettings.Collect.ALL)
                    .fields(listOf(EvalCreateParams.GitMetadataSettings.Field.COMMIT))
                    .build()
            )
        assertThat(body.isPublic()).isEqualTo(true)
        assertThat(body.maxConcurrency()).isEqualTo(42.23)
        assertThat(body.metadata()).isEqualTo(EvalCreateParams.Metadata.builder().build())
        assertThat(body.repoInfo())
            .isEqualTo(
                RepoInfo.builder()
                    .authorEmail("author_email")
                    .authorName("author_name")
                    .branch("branch")
                    .commit("commit")
                    .commitMessage("commit_message")
                    .commitTime("commit_time")
                    .dirty(true)
                    .gitDiff("git_diff")
                    .tag("tag")
                    .build()
            )
        assertThat(body.stream()).isEqualTo(true)
        assertThat(body.timeout()).isEqualTo(42.23)
        assertThat(body.trialCount()).isEqualTo(42.23)
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            EvalCreateParams.builder()
                .data(
                    EvalCreateParams.Data.ofDatasetId(
                        EvalCreateParams.Data.DatasetId.builder().datasetId("dataset_id").build()
                    )
                )
                .projectId("project_id")
                .scores(
                    listOf(
                        EvalCreateParams.Score.ofFunctionId(
                            EvalCreateParams.Score.FunctionId.builder()
                                .functionId("function_id")
                                .build()
                        )
                    )
                )
                .task(
                    EvalCreateParams.Task.ofFunctionId(
                        EvalCreateParams.Task.FunctionId.builder().functionId("function_id").build()
                    )
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.data())
            .isEqualTo(
                EvalCreateParams.Data.ofDatasetId(
                    EvalCreateParams.Data.DatasetId.builder().datasetId("dataset_id").build()
                )
            )
        assertThat(body.projectId()).isEqualTo("project_id")
        assertThat(body.scores())
            .isEqualTo(
                listOf(
                    EvalCreateParams.Score.ofFunctionId(
                        EvalCreateParams.Score.FunctionId.builder()
                            .functionId("function_id")
                            .build()
                    )
                )
            )
        assertThat(body.task())
            .isEqualTo(
                EvalCreateParams.Task.ofFunctionId(
                    EvalCreateParams.Task.FunctionId.builder().functionId("function_id").build()
                )
            )
    }
}
