configured_endpoints: 57
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/manugoyal%2Fbraintrust-sdk-kotlin-a3cf5e2cde79fce2f8d595cfd5c3b44db6d2a5499e4623e62b5c280646867552.yml
