configured_endpoints: 59
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/manugoyal%2Fbraintrust-sdk-kotlin-5288a4806318bef69f9601b1cd29c037e012b58855a47c6c043cf6993df53c02.yml
