configured_endpoints: 59
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/manugoyal%2Fbraintrust-sdk-kotlin-50a4a8b20186309e5a22925f731fee3de9511b7047bef155a0c4fa9edaf7dc1b.yml
