configured_endpoints: 57
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/manugoyal%2Fbraintrust-sdk-kotlin-44b51ad3239a0d86e832a267339339cc1727c967a62b4ac9a419eeba7085a62c.yml
