configured_endpoints: 59
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/manugoyal%2Fbraintrust-sdk-kotlin-8c69b494e9958f062448f0e4bd2a61abccb4a223502869729fea0565f91ffaca.yml
