// File generated from our OpenAPI spec by Stainless.

package com.braintrust.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PromptRetrieveResponseTest {

    @Test
    fun createPromptRetrieveResponse() {
        val promptRetrieveResponse =
            PromptRetrieveResponse.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                ._xactId("string")
                .logId(PromptRetrieveResponse.LogId.P)
                .name("string")
                .orgId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .slug("string")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .description("string")
                .metadata(PromptRetrieveResponse.Metadata.builder().build())
                .promptData(
                    PromptRetrieveResponse.PromptData.builder()
                        .options(
                            PromptRetrieveResponse.PromptData.Options.builder()
                                .model("string")
                                .params(
                                    PromptRetrieveResponse.PromptData.Options.Params.ofUnionMember0(
                                        PromptRetrieveResponse.PromptData.Options.Params
                                            .UnionMember0
                                            .builder()
                                            .frequencyPenalty(42.23)
                                            .functionCall(
                                                PromptRetrieveResponse.PromptData.Options.Params
                                                    .UnionMember0
                                                    .FunctionCall
                                                    .ofUnionMember0(
                                                        PromptRetrieveResponse.PromptData.Options
                                                            .Params
                                                            .UnionMember0
                                                            .FunctionCall
                                                            .UnionMember0
                                                            .AUTO
                                                    )
                                            )
                                            .maxTokens(42.23)
                                            .n(42.23)
                                            .presencePenalty(42.23)
                                            .responseFormat(
                                                PromptRetrieveResponse.PromptData.Options.Params
                                                    .UnionMember0
                                                    .ResponseFormat
                                                    .builder()
                                                    .type(
                                                        PromptRetrieveResponse.PromptData.Options
                                                            .Params
                                                            .UnionMember0
                                                            .ResponseFormat
                                                            .Type
                                                            .JSON_OBJECT
                                                    )
                                                    .build()
                                            )
                                            .stop(listOf("string"))
                                            .temperature(42.23)
                                            .toolChoice(
                                                PromptRetrieveResponse.PromptData.Options.Params
                                                    .UnionMember0
                                                    .ToolChoice
                                                    .ofUnionMember0(
                                                        PromptRetrieveResponse.PromptData.Options
                                                            .Params
                                                            .UnionMember0
                                                            .ToolChoice
                                                            .UnionMember0
                                                            .AUTO
                                                    )
                                            )
                                            .topP(42.23)
                                            .useCache(true)
                                            .build()
                                    )
                                )
                                .position("string")
                                .build()
                        )
                        .origin(
                            PromptRetrieveResponse.PromptData.Origin.builder()
                                .projectId("string")
                                .promptId("string")
                                .promptVersion("string")
                                .build()
                        )
                        .prompt(
                            PromptRetrieveResponse.PromptData.Prompt.ofUnionMember0(
                                PromptRetrieveResponse.PromptData.Prompt.UnionMember0.builder()
                                    .content("string")
                                    .type(
                                        PromptRetrieveResponse.PromptData.Prompt.UnionMember0.Type
                                            .COMPLETION
                                    )
                                    .build()
                            )
                        )
                        .build()
                )
                .tags(listOf("string"))
                .build()
        assertThat(promptRetrieveResponse).isNotNull
        assertThat(promptRetrieveResponse.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(promptRetrieveResponse._xactId()).isEqualTo("string")
        assertThat(promptRetrieveResponse.logId()).isEqualTo(PromptRetrieveResponse.LogId.P)
        assertThat(promptRetrieveResponse.name()).isEqualTo("string")
        assertThat(promptRetrieveResponse.orgId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(promptRetrieveResponse.projectId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(promptRetrieveResponse.slug()).isEqualTo("string")
        assertThat(promptRetrieveResponse.created())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(promptRetrieveResponse.description()).contains("string")
        assertThat(promptRetrieveResponse.metadata())
            .contains(PromptRetrieveResponse.Metadata.builder().build())
        assertThat(promptRetrieveResponse.promptData())
            .contains(
                PromptRetrieveResponse.PromptData.builder()
                    .options(
                        PromptRetrieveResponse.PromptData.Options.builder()
                            .model("string")
                            .params(
                                PromptRetrieveResponse.PromptData.Options.Params.ofUnionMember0(
                                    PromptRetrieveResponse.PromptData.Options.Params.UnionMember0
                                        .builder()
                                        .frequencyPenalty(42.23)
                                        .functionCall(
                                            PromptRetrieveResponse.PromptData.Options.Params
                                                .UnionMember0
                                                .FunctionCall
                                                .ofUnionMember0(
                                                    PromptRetrieveResponse.PromptData.Options.Params
                                                        .UnionMember0
                                                        .FunctionCall
                                                        .UnionMember0
                                                        .AUTO
                                                )
                                        )
                                        .maxTokens(42.23)
                                        .n(42.23)
                                        .presencePenalty(42.23)
                                        .responseFormat(
                                            PromptRetrieveResponse.PromptData.Options.Params
                                                .UnionMember0
                                                .ResponseFormat
                                                .builder()
                                                .type(
                                                    PromptRetrieveResponse.PromptData.Options.Params
                                                        .UnionMember0
                                                        .ResponseFormat
                                                        .Type
                                                        .JSON_OBJECT
                                                )
                                                .build()
                                        )
                                        .stop(listOf("string"))
                                        .temperature(42.23)
                                        .toolChoice(
                                            PromptRetrieveResponse.PromptData.Options.Params
                                                .UnionMember0
                                                .ToolChoice
                                                .ofUnionMember0(
                                                    PromptRetrieveResponse.PromptData.Options.Params
                                                        .UnionMember0
                                                        .ToolChoice
                                                        .UnionMember0
                                                        .AUTO
                                                )
                                        )
                                        .topP(42.23)
                                        .useCache(true)
                                        .build()
                                )
                            )
                            .position("string")
                            .build()
                    )
                    .origin(
                        PromptRetrieveResponse.PromptData.Origin.builder()
                            .projectId("string")
                            .promptId("string")
                            .promptVersion("string")
                            .build()
                    )
                    .prompt(
                        PromptRetrieveResponse.PromptData.Prompt.ofUnionMember0(
                            PromptRetrieveResponse.PromptData.Prompt.UnionMember0.builder()
                                .content("string")
                                .type(
                                    PromptRetrieveResponse.PromptData.Prompt.UnionMember0.Type
                                        .COMPLETION
                                )
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(promptRetrieveResponse.tags().get()).containsExactly("string")
    }
}
