// File generated from our OpenAPI spec by Stainless.

package com.braintrust.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PromptCreateResponseTest {

    @Test
    fun createPromptCreateResponse() {
        val promptCreateResponse =
            PromptCreateResponse.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                ._xactId("string")
                .logId(PromptCreateResponse.LogId.P)
                .name("string")
                .orgId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .slug("string")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .description("string")
                .metadata(PromptCreateResponse.Metadata.builder().build())
                .promptData(
                    PromptCreateResponse.PromptData.builder()
                        .options(
                            PromptCreateResponse.PromptData.Options.builder()
                                .model("string")
                                .params(
                                    PromptCreateResponse.PromptData.Options.Params.ofUnionMember0(
                                        PromptCreateResponse.PromptData.Options.Params.UnionMember0
                                            .builder()
                                            .frequencyPenalty(42.23)
                                            .functionCall(
                                                PromptCreateResponse.PromptData.Options.Params
                                                    .UnionMember0
                                                    .FunctionCall
                                                    .ofUnionMember0(
                                                        PromptCreateResponse.PromptData.Options
                                                            .Params
                                                            .UnionMember0
                                                            .FunctionCall
                                                            .UnionMember0
                                                            .AUTO
                                                    )
                                            )
                                            .maxTokens(42.23)
                                            .n(42.23)
                                            .presencePenalty(42.23)
                                            .responseFormat(
                                                PromptCreateResponse.PromptData.Options.Params
                                                    .UnionMember0
                                                    .ResponseFormat
                                                    .builder()
                                                    .type(
                                                        PromptCreateResponse.PromptData.Options
                                                            .Params
                                                            .UnionMember0
                                                            .ResponseFormat
                                                            .Type
                                                            .JSON_OBJECT
                                                    )
                                                    .build()
                                            )
                                            .stop(listOf("string"))
                                            .temperature(42.23)
                                            .toolChoice(
                                                PromptCreateResponse.PromptData.Options.Params
                                                    .UnionMember0
                                                    .ToolChoice
                                                    .ofUnionMember0(
                                                        PromptCreateResponse.PromptData.Options
                                                            .Params
                                                            .UnionMember0
                                                            .ToolChoice
                                                            .UnionMember0
                                                            .AUTO
                                                    )
                                            )
                                            .topP(42.23)
                                            .useCache(true)
                                            .build()
                                    )
                                )
                                .position("string")
                                .build()
                        )
                        .origin(
                            PromptCreateResponse.PromptData.Origin.builder()
                                .projectId("string")
                                .promptId("string")
                                .promptVersion("string")
                                .build()
                        )
                        .prompt(
                            PromptCreateResponse.PromptData.Prompt.ofUnionMember0(
                                PromptCreateResponse.PromptData.Prompt.UnionMember0.builder()
                                    .content("string")
                                    .type(
                                        PromptCreateResponse.PromptData.Prompt.UnionMember0.Type
                                            .COMPLETION
                                    )
                                    .build()
                            )
                        )
                        .build()
                )
                .tags(listOf("string"))
                .build()
        assertThat(promptCreateResponse).isNotNull
        assertThat(promptCreateResponse.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(promptCreateResponse._xactId()).isEqualTo("string")
        assertThat(promptCreateResponse.logId()).isEqualTo(PromptCreateResponse.LogId.P)
        assertThat(promptCreateResponse.name()).isEqualTo("string")
        assertThat(promptCreateResponse.orgId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(promptCreateResponse.projectId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(promptCreateResponse.slug()).isEqualTo("string")
        assertThat(promptCreateResponse.created())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(promptCreateResponse.description()).contains("string")
        assertThat(promptCreateResponse.metadata())
            .contains(PromptCreateResponse.Metadata.builder().build())
        assertThat(promptCreateResponse.promptData())
            .contains(
                PromptCreateResponse.PromptData.builder()
                    .options(
                        PromptCreateResponse.PromptData.Options.builder()
                            .model("string")
                            .params(
                                PromptCreateResponse.PromptData.Options.Params.ofUnionMember0(
                                    PromptCreateResponse.PromptData.Options.Params.UnionMember0
                                        .builder()
                                        .frequencyPenalty(42.23)
                                        .functionCall(
                                            PromptCreateResponse.PromptData.Options.Params
                                                .UnionMember0
                                                .FunctionCall
                                                .ofUnionMember0(
                                                    PromptCreateResponse.PromptData.Options.Params
                                                        .UnionMember0
                                                        .FunctionCall
                                                        .UnionMember0
                                                        .AUTO
                                                )
                                        )
                                        .maxTokens(42.23)
                                        .n(42.23)
                                        .presencePenalty(42.23)
                                        .responseFormat(
                                            PromptCreateResponse.PromptData.Options.Params
                                                .UnionMember0
                                                .ResponseFormat
                                                .builder()
                                                .type(
                                                    PromptCreateResponse.PromptData.Options.Params
                                                        .UnionMember0
                                                        .ResponseFormat
                                                        .Type
                                                        .JSON_OBJECT
                                                )
                                                .build()
                                        )
                                        .stop(listOf("string"))
                                        .temperature(42.23)
                                        .toolChoice(
                                            PromptCreateResponse.PromptData.Options.Params
                                                .UnionMember0
                                                .ToolChoice
                                                .ofUnionMember0(
                                                    PromptCreateResponse.PromptData.Options.Params
                                                        .UnionMember0
                                                        .ToolChoice
                                                        .UnionMember0
                                                        .AUTO
                                                )
                                        )
                                        .topP(42.23)
                                        .useCache(true)
                                        .build()
                                )
                            )
                            .position("string")
                            .build()
                    )
                    .origin(
                        PromptCreateResponse.PromptData.Origin.builder()
                            .projectId("string")
                            .promptId("string")
                            .promptVersion("string")
                            .build()
                    )
                    .prompt(
                        PromptCreateResponse.PromptData.Prompt.ofUnionMember0(
                            PromptCreateResponse.PromptData.Prompt.UnionMember0.builder()
                                .content("string")
                                .type(
                                    PromptCreateResponse.PromptData.Prompt.UnionMember0.Type
                                        .COMPLETION
                                )
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(promptCreateResponse.tags().get()).containsExactly("string")
    }
}
