// File generated from our OpenAPI spec by Stainless.

package com.braintrust.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PromptTest {

    @Test
    fun createPrompt() {
        val prompt =
            Prompt.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                ._xactId("string")
                .logId(Prompt.LogId.P)
                .name("string")
                .orgId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .slug("string")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .description("string")
                .metadata(Prompt.Metadata.builder().build())
                .promptData(
                    Prompt.PromptData.builder()
                        .options(
                            Prompt.PromptData.Options.builder()
                                .model("string")
                                .params(
                                    Prompt.PromptData.Options.Params.ofUnionMember0(
                                        Prompt.PromptData.Options.Params.UnionMember0.builder()
                                            .frequencyPenalty(42.23)
                                            .functionCall(
                                                Prompt.PromptData.Options.Params.UnionMember0
                                                    .FunctionCall
                                                    .ofUnionMember0(
                                                        Prompt.PromptData.Options.Params
                                                            .UnionMember0
                                                            .FunctionCall
                                                            .UnionMember0
                                                            .AUTO
                                                    )
                                            )
                                            .maxTokens(42.23)
                                            .n(42.23)
                                            .presencePenalty(42.23)
                                            .responseFormat(
                                                Prompt.PromptData.Options.Params.UnionMember0
                                                    .ResponseFormat
                                                    .builder()
                                                    .type(
                                                        Prompt.PromptData.Options.Params
                                                            .UnionMember0
                                                            .ResponseFormat
                                                            .Type
                                                            .JSON_OBJECT
                                                    )
                                                    .build()
                                            )
                                            .stop(listOf("string"))
                                            .temperature(42.23)
                                            .toolChoice(
                                                Prompt.PromptData.Options.Params.UnionMember0
                                                    .ToolChoice
                                                    .ofUnionMember0(
                                                        Prompt.PromptData.Options.Params
                                                            .UnionMember0
                                                            .ToolChoice
                                                            .UnionMember0
                                                            .AUTO
                                                    )
                                            )
                                            .topP(42.23)
                                            .useCache(true)
                                            .build()
                                    )
                                )
                                .position("string")
                                .build()
                        )
                        .origin(
                            Prompt.PromptData.Origin.builder()
                                .projectId("string")
                                .promptId("string")
                                .promptVersion("string")
                                .build()
                        )
                        .prompt(
                            Prompt.PromptData.Prompt.ofUnionMember0(
                                Prompt.PromptData.Prompt.UnionMember0.builder()
                                    .content("string")
                                    .type(Prompt.PromptData.Prompt.UnionMember0.Type.COMPLETION)
                                    .build()
                            )
                        )
                        .build()
                )
                .tags(listOf("string"))
                .build()
        assertThat(prompt).isNotNull
        assertThat(prompt.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(prompt._xactId()).isEqualTo("string")
        assertThat(prompt.logId()).isEqualTo(Prompt.LogId.P)
        assertThat(prompt.name()).isEqualTo("string")
        assertThat(prompt.orgId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(prompt.projectId()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(prompt.slug()).isEqualTo("string")
        assertThat(prompt.created()).contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(prompt.description()).contains("string")
        assertThat(prompt.metadata()).contains(Prompt.Metadata.builder().build())
        assertThat(prompt.promptData())
            .contains(
                Prompt.PromptData.builder()
                    .options(
                        Prompt.PromptData.Options.builder()
                            .model("string")
                            .params(
                                Prompt.PromptData.Options.Params.ofUnionMember0(
                                    Prompt.PromptData.Options.Params.UnionMember0.builder()
                                        .frequencyPenalty(42.23)
                                        .functionCall(
                                            Prompt.PromptData.Options.Params.UnionMember0
                                                .FunctionCall
                                                .ofUnionMember0(
                                                    Prompt.PromptData.Options.Params.UnionMember0
                                                        .FunctionCall
                                                        .UnionMember0
                                                        .AUTO
                                                )
                                        )
                                        .maxTokens(42.23)
                                        .n(42.23)
                                        .presencePenalty(42.23)
                                        .responseFormat(
                                            Prompt.PromptData.Options.Params.UnionMember0
                                                .ResponseFormat
                                                .builder()
                                                .type(
                                                    Prompt.PromptData.Options.Params.UnionMember0
                                                        .ResponseFormat
                                                        .Type
                                                        .JSON_OBJECT
                                                )
                                                .build()
                                        )
                                        .stop(listOf("string"))
                                        .temperature(42.23)
                                        .toolChoice(
                                            Prompt.PromptData.Options.Params.UnionMember0.ToolChoice
                                                .ofUnionMember0(
                                                    Prompt.PromptData.Options.Params.UnionMember0
                                                        .ToolChoice
                                                        .UnionMember0
                                                        .AUTO
                                                )
                                        )
                                        .topP(42.23)
                                        .useCache(true)
                                        .build()
                                )
                            )
                            .position("string")
                            .build()
                    )
                    .origin(
                        Prompt.PromptData.Origin.builder()
                            .projectId("string")
                            .promptId("string")
                            .promptVersion("string")
                            .build()
                    )
                    .prompt(
                        Prompt.PromptData.Prompt.ofUnionMember0(
                            Prompt.PromptData.Prompt.UnionMember0.builder()
                                .content("string")
                                .type(Prompt.PromptData.Prompt.UnionMember0.Type.COMPLETION)
                                .build()
                        )
                    )
                    .build()
            )
        assertThat(prompt.tags().get()).containsExactly("string")
    }
}
